### ISSUE TITLE
Ancient Cave Request

### ISSUE THREAD

**Issue by Fackey** [abyssonym/grand_cross#4]

**Comment by abyssonym** [comment]
I don't plan to add an Ancient Cave mode to this randomizer. However, you might want to keep an eye on the GBA version randomizer, for which I hear there are plans to include an Ancient Cave mode: http://gamerandomizers.wikia.com/wiki/Final_Fantasy_V_Advance_Randomizer

**Comment by Fackey** [comment]
Thank you for your reply, and thank you for the suggestion, I will keep an
eye on it.
