### ISSUE TITLE
Several Random Chest Issues

### ISSUE THREAD

**Issue by SoraHjort** [abyssonym/grand_cross#5]
I've ran into three issues with the Random Treasure flag.
1. I've gotten Demi over 6 times so far, only just go through the water crystal. Quite a bit of waste getting the same magic spell over and over
2. I've ran into several chests, and item spots, where there was nothing. No pop up saying I got a item, nor chest visually opening.
3. I've ran into a single instance, so far, of a null item. 
Seen here: ![ffv_orig cpty 1527746026000](https://user-images.githubusercontent.com/18604504/40782313-5740bdbc-648b-11e8-9cea-1465af82a4c3.png)

Honestly, when I see this, to me it seems like the best option from a player standpoint, would to have the treasure spots shuffle, instead of having a pure random selection. Such as say having the contents of a treasure chest in Tycoon Castle placed in to an item spot in Carwen. Much like how the randomizers for Link to the Past and Super Metroid work.

Maybe have that as it's own separate flag, so people can either chose shuffle random, or pure randomize selection. Heck you could also throw in a flag to also shuffle treasures with the shops.

Of course, that would likely require quite a bit of reprogramming for the randomizer. And it hasn't been updated in two years. So I'm not exactly holding my breath. But if you ever do an update, I would recommend consider doing this.

Seed: 1527746026000
Flags: CYPT
Original Rom Version: RPGe 1.1

**Comment by abyssonym** [comment]
All of this stuff is basically fixed as of version 6. The current version will only have spell chests that were present in the original game, the item randomization performs more checks to ensure valid treasure, and a glitch was fixed that made some chests unopenable.
